// lib/models/notification_model.dart
// No Supabase import needed if not using Supabase types.

class NotificationModel {
  final String id; // UUID, final
  final String userId; // UUID of the user this notification belongs to, final
  String title;
  String body;
  String? type; // e.g., 'quest_complete', 'achievement_unlocked'
  String? referenceId; // e.g., quest_id, achievement_id. Can be UUID or other string.
  bool isRead;
  final DateTime createdAt; // Should be non-nullable as DB has NOT NULL DEFAULT NOW()

  NotificationModel({
    required this.id,
    required this.userId,
    required this.title,
    required this.body,
    this.type,
    this.referenceId,
    required this.createdAt, // Made required
    this.isRead = false,
  });

  factory NotificationModel.fromSupabase(Map<String, dynamic> data) {
    return NotificationModel(
      id: data['id'] as String, // Should always exist
      userId: data['user_id'] as String? ?? '', // Should always exist, but defensive null check
      title: data['title'] as String? ?? 'No Title',
      body: data['body'] as String? ?? 'No Body',
      type: data['type'] as String?,
      referenceId: data['reference_id'] as String?, // Mapped from snake_case
      // createdAt should always exist due to DB default and NOT NULL constraint.
      // If it can somehow be null from a response, DateTime.now() is a fallback.
      createdAt: data['created_at'] != null
          ? DateTime.parse(data['created_at'] as String) // Use parse, tryParse if it could be invalid format
          : DateTime.now(), // Fallback, though ideally DB ensures this is always set
      isRead: (data['is_read'] ?? false) as bool,
    );
  }

  Map<String, dynamic> toSupabase() {
    // This map is primarily for creating a new notification.
    // 'id' and 'created_at' are generated by the database.
    // 'is_read' defaults to false on insert.
    // Updates to 'is_read' are usually specific operations (e.g., markAsRead).
    return {
      'user_id': userId,
      'title': title,
      'body': body,
      if (type != null) 'type': type,
      if (referenceId != null) 'reference_id': referenceId,
      // 'is_read': isRead, // Typically not set directly on creation, defaults to false
      // 'created_at': handled by DB
    };
  }
}
